config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :restaurants do
    resources :plates, only: [:new, :create]
  end
  resources :plates, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plate.rb
class Plate < ApplicationRecord
  belongs_to :restaurant
  has_one_attached :photo

  validates :name, presence: true
  validates :rating, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :plates, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  def show
    @plate = Plate.find(params[:id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @plate = Plate.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @plate = Plate.new(plate_params)
    @plate.restaurant = @restaurant
    if @plate.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @plate = Plate.find(params[:id])
    @plate.destroy
    redirect_to restaurant_path(@plate.restaurant)
  end

  private

  def plate_params
    params.require(:plate).permit(:name, :rating, :comment, :price, :photo)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(params[:restaurant])
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rate My Plate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- BANNER -->
  <div class="banner">
    <!-- NAVBAR -->
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-home">
      <%= link_to restaurants_path, class: "navbar-brand" do %>
        <i class="fas fa-utensils"></i>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!-- <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li> -->
          <li class="nav-item active">
            <%= link_to "Add Restaurant", new_restaurant_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
  <!--           <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
   -->          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="container">
      <h1>RATE MY PLATE</h1>
      <hr class="banner-hr">
      <p>Keep track of all of your favorites dishes from <br> all of your favorite restaurants</p>
      <%= link_to "Rate Now", restaurants_path, class: 'btn btn-banner' %>
    </div>
  </div>

<!-- ICONS -->
<div class="icon">

</div>

app/views/plates/_form.html.erb
<%= simple_form_for [@restaurant, @plate] do |f| %>
  <%= f.input :name, label: false, placeholder: 'Name', error: 'Name is mandatory, please specify one' %>
  <%= f.input :rating, collection: (1..5).to_a, label: 'Rate Your Plate' %>
  <%= f.input :price, label: false, placeholder: 'Price' %>
  <%= f.input :comment, label: false, placeholder: 'Comment' %>
  <%= f.input :photo, input_html: { class: 'd-none' }, label_html: { class: 'btn-upload-photo'}, label: '📷 Upload a photo' %>
  <%= f.submit "Add", class: 'btn-add'%>
<% end %>

app/views/plates/new.html.erb
<div class="container form-container">
  <h1 class="form-header">Add a New Plate</h1>
  <%= render 'plates/form' %>
  <%= link_to "Cancel", restaurant_path(@restaurant), class: "btn-back" %>
</div>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name, label: false, placeholder: 'Name', error: 'Name is mandatory, please specify one' %>
  <%= f.input :address, label: false, placeholder: 'Address' %>
  <%= f.input :rating, collection: (1..5).to_a, label: 'Rate the Restaurant' %>
  <%= f.input :photo, input_html: { class: 'd-none' }, label_html: { class: 'btn-upload-photo'}, label: '📷 Upload a photo' %>
  <%= f.submit "Add", class: "btn-add" %>
<% end %>

app/views/restaurants/index.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to restaurants_path, class: "navbar-brand" do %>
      <i class="fas fa-utensils"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <!-- <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li> -->
        <li class="nav-item active">
          <%= link_to "Add Restaurant", new_restaurant_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
<!--           <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
 -->          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>

<div class="container">
  <div class="restaurant-header">
    <h1>My Restaurants</h1>
  </div>

  <div class="cards">
    <% @restaurants.each do |restaurant| %>
      <div class="card-trip">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
        <div class="card-trip-infos">
          <div>
            <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
            <p>
              <% if restaurant.rating == 1 %>
                <%= "⭐️" %>
              <% elsif restaurant.rating == 2 %>
                <%= "⭐️⭐️" %>
              <% elsif restaurant.rating == 3 %>
                <%= "⭐️⭐️⭐️" %>
              <% elsif restaurant.rating == 4 %>
                <%= "⭐️⭐️⭐️⭐️" %>
              <% else restaurant.rating == 5 %>
                <%= "⭐️⭐️⭐️⭐️⭐️" %>
              <% end %>
            </p>
          </div>
          <h2 class="card-trip-pricing">¥<%= restaurant.price %></h2>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container form-container">
  <h1 class="form-header">Add a New Restaurant</h1>
  <%= render 'restaurants/form' %>
  <%= link_to "Cancel", restaurants_path, class: "btn-back" %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="restaurant-info">
    <h2 class="restaurant-header"><%= @restaurant.name %></h2>
    <p><%= @restaurant.address %></p>
    <p>
      <% if @restaurant.rating == 1 %>
        <%= "⭐️" %>
      <% elsif @restaurant.rating == 2 %>
        <%= "⭐️ ⭐️" %>
      <% elsif @restaurant.rating == 3 %>
        <%= "⭐️ ⭐️ ⭐️" %>
      <% elsif @restaurant.rating == 4 %>
        <%= "⭐️ ⭐️ ⭐️ ⭐️" %>
      <% else @restaurant.rating == 5 %>
        <%= "⭐️ ⭐️ ⭐️ ⭐️ ⭐️" %>
      <% end %>
    </p>
  </div>

  <div class="plate-list">
    <% @restaurant.plates.each do |plate| %>
      <div class="card-product">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <div class="card-product-infos">
          <h2><%= plate.name %></h2>
          <p>
            <% if @restaurant.rating == 1 %>
              <%= "⭐️" %>
            <% elsif @restaurant.rating == 2 %>
              <%= "⭐️ ⭐️" %>
            <% elsif @restaurant.rating == 3 %>
              <%= "⭐️ ⭐️ ⭐️" %>
            <% elsif @restaurant.rating == 4 %>
              <%= "⭐️ ⭐️ ⭐️ ⭐️" %>
            <% else @restaurant.rating == 5 %>
              <%= "⭐️ ⭐️ ⭐️ ⭐️ ⭐️" %>
            <% end %>
          </p>
          <p>¥<%= plate.price %></p>
          <p><%= plate.comment %></p>
        </div>
      </div>
    <% end %>
  </div>

  <div class="action">
    <%= link_to "Add a New Plate", new_restaurant_plate_path(@restaurant), class: 'btn btn-add' %>
    <%= link_to "Go Back", restaurants_path, class: 'btn-back' %>
  </div>

</div>